networks:
  gift:
    driver: bridge

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8083:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gift

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - gift

  php_appli:
    image: canals/php:latest
    ports:
      - "8082:80"
    volumes:
      - "./gift.appli/public:/var/www/html"
      - "./gift.appli/src:/var/www/src"
    networks:
      - gift

  php_api:
    image: canals/php:latest
    ports:
      - "8084:80"
    volumes:
      - "./gift.api/public:/var/www/html"
      - "./gift.api/src:/var/www/src"
    networks:
      - gift
