version: '3.9'

networks:
  gift:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8083:3306"
    networks:
      - gift

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - gift

  php:
    image: canals/php:latest
    ports:
      - "8082:80"
    volumes :
      - "./public:/var/www/html"
      - "./src:/var/www/src"
    networks:
      - gift